### ISSUE TITLE
Sectionalize Favorites

### ISSUE THREAD

**Issue by OnlyInAmerica** [Burning-Man-Earth/iBurn-iOS#43] opened 2015-08-17 15:09 UTC
It would be really sweet to see your favorited items organized into sections like in Explore. Currently favorites are groups (Art, then Camps, then Events) but there are no headers so this isn't obvious.

It would be extra really sweet if we could sort the Event section by start time, instead of name. This would let you browse your favorited events like a schedule (sorted by start time, not A-Z).

**Comment by chrisballinger** [comment] 2015-08-17 19:59
Duplicate of https://github.com/Burning-Man-Earth/iBurn-iOS/issues/23

The event section is already sorted by start time 👍🏼

**Closed by chrisballinger** 2015-08-17 19:59 UTC
Labels: Feature

**Comment by OnlyInAmerica** [comment] 2015-08-17 20:11
Right on. I missed this because the event stat time labels can be a little confusing since they don't show date (even if they're several days out).

E.g: An event starting 8:00a today and an event starting 8:00a two days from now display as "8:00 a". Would be great to print these differently "8:00a Tuesday" vs "8:00a" (Today).

![iBurn fav sort](http://i.imgur.com/kesskq8.png)

**Comment by chrisballinger** [comment] 2015-08-17 20:16
Ohhh I see! That's a good idea!

The cell not showing day of week is an issue on the global map search
function as well
